export const dailyReminders = [
  "Let’s get moving! Complete a 20-minute workout or walk 10,000 steps today.",
  "Time to learn! Spend 30 minutes reading or studying something new.",
  "Take a moment to relax. Meditate for 5 minutes for inner peace.",
  "Stay hydrated! Drink a glass of water to refresh your body.",
  "Reflect on your blessings. Write down 3 things you're grateful for today.",
  "Call or message a loved one and make their day brighter.",
  "Spend a few minutes organizing your workspace for clarity.",
  "Take a short walk outside and enjoy the fresh air.",
  "Eat something nutritious that fuels your energy.",
  "Write down one goal you want to achieve this week.",
  "Take deep breaths — inhale calm, exhale stress.",
  "Compliment someone sincerely today.",
  "Unplug from screens for 10 minutes to reset your mind.",
  "Listen to your favorite song and dance like no one’s watching!",
  "Try something creative today — draw, write, or cook.",
  "Plan tomorrow’s top 3 priorities before going to bed.",
  "Smile intentionally — it improves your mood instantly.",
  "Help someone without expecting anything in return.",
  "Spend a few minutes stretching your body.",
  "Think of one habit you want to improve and take a small step toward it.",
  "Drink green tea or water instead of soda today.",
  "Appreciate nature — look at the sky, trees, or birds around you.",
  "Set aside 15 minutes for a hobby you love.",
  "Listen to a motivational podcast or TED talk.",
  "Write a thank-you note to someone who helped you recently.",
  "Forgive yourself for past mistakes — move forward kindly.",
  "Take a power nap if you feel drained.",
  "Eat slowly and enjoy every bite mindfully.",
  "Do one small act of kindness today.",
  "Check your posture — sit or stand tall!",
  "Declutter one small area of your room or desk.",
  "Spend 10 minutes journaling your thoughts.",
  "Make a budget check — are you on track this week?",
  "Read one inspiring quote and reflect on it.",
  "Close your eyes and focus on your breathing for 60 seconds.",
  "Send a voice note instead of a text to make it more personal.",
  "Avoid negativity — focus on what you can control.",
  "Take a cold shower to refresh your body and mind.",
  "Compliment yourself — you’re doing better than you think.",
  "Cook or order your favorite healthy meal.",
  "Review your goals and see what progress you’ve made.",
  "Go to bed early and prioritize sleep tonight.",
  "Limit social media for one hour and use that time mindfully.",
  "Celebrate a small win — progress counts!",
  "Give someone a genuine smile today.",
  "Hydrate before your morning coffee.",
  "Say ‘thank you’ more often today.",
  "Take a digital detox for 15 minutes.",
  "Make a to-do list for tomorrow.",
  "Watch something that inspires you.",
  "Avoid multitasking — do one thing at a time.",
  "Practice patience with others and yourself.",
  "Do one thing that scares you a little.",
  "Stand up and stretch your shoulders.",
  "Reflect on one lesson you learned this week.",
  "Declutter your phone — delete unnecessary apps or photos.",
  "Do something kind for future-you (prep breakfast or organize).",
  "Spend 5 minutes visualizing your dream life.",
  "Give yourself permission to rest without guilt.",
  "Compliment a coworker or friend on something specific.",
  "Track one positive habit today.",
  "Drink a full glass of water before every meal.",
  "Listen to your favorite relaxing music.",
  "Avoid complaining for one whole day.",
  "Do something nice for a stranger.",
  "Wake up 10 minutes earlier tomorrow.",
  "Laugh out loud — it’s good for your soul.",
  "Make a list of your top strengths.",
  "Read something that expands your mindset.",
  "Tidy your digital workspace.",
  "Forgive someone who hurt you, silently and peacefully.",
  "Say something positive to yourself in the mirror.",
  "Spend a few minutes stretching before bed.",
  "Donate or share something you don’t use anymore.",
  "Do 10 push-ups or squats right now!",
  "Try a new recipe or healthy snack.",
  "Take time to appreciate yourself today.",
  "Plan one fun thing for the weekend.",
  "Write down your thoughts before sleeping.",
  "Avoid negative news for a few hours.",
  "Take a mindful deep breath before replying to any stress.",
  "Spend 10 minutes in silence.",
  "Celebrate your small progress steps.",
  "Help someone without telling anyone.",
  "Smile at three people today.",
  "Check in with your goals monthly.",
  "Take the stairs instead of the elevator.",
  "Unsubscribe from unnecessary emails.",
  "Reward yourself for staying consistent.",
  "Speak kindly to yourself all day.",
  "Drink a glass of water right now.",
  "Be fully present in your next conversation.",
  "Clean up your workspace before lunch.",
  "Plan something new to learn next week.",
  "Read a few pages of a positive book.",
  "Take a break and go outside for sunlight.",
  "Express gratitude to someone today.",
  "Reflect on how far you’ve come this year.",
  "Be gentle with yourself today.",
  "Stretch before starting work.",
  "Trust your journey — you’re growing every day."
];
